class Icon
  ANALYTICS = 'bi bi-activity'
  DASHBOARD = 'bi bi-grid-fill'
  TECHNIC = 'bi bi-pencil-fill'
  ACTOR = 'bi bi-people-fill'
  MATERIAL = 'bi bi-box-fill'
  PAGE = 'bi bi-file-earmark-fill'
  DEFINITION = 'bi bi-body-text'
  PRODUCT = 'bi bi-tag-fill'
  PROJECT = 'bi bi-star-fill'
  REGION = 'bi bi-geo-alt-fill'
  STRUCTURE = 'bi bi-gear-fill'
  USER = 'bi bi-person-fill'

  FOLDER_CLOSED = 'bi bi-folder'
  FOLDER_OPENED = 'bi bi-folder-symlink'
  FOLDER_CLOSED_FULL = 'bi bi-folder-fill'
  FOLDER_OPENED_FULL = 'bi bi-folder-symlink-fill'
  SORT = 'bi bi-arrow-down-up'
  MOVE = 'bi bi-arrows-move'
  EDIT = 'bi bi-pen'
  ADD = 'bi bi-plus'
  DELETE = 'bi bi-trash'
end
